export const conformanceEnv = {
  "version": '121.0.6166.0',
  'last_update': 'Dec 6, 2023'
}
export const conformance = [
  { "name": "densenet", "backend": "wasm_4", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "1e-3", "e4": "1e-4", "e5": "1e-5" }, { "name": "densenet", "backend": "webnn_cpu_4", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "fail" }, { "name": "densenet", "backend": "webgl", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "pass" }, { "name": "densenet", "backend": "webgpu", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "fail" }, { "name": "densenet", "backend": "webnn_gpu", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "pass" },
  { "name": "efficientnet_lite", "backend": "wasm_4", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "1e-3", "e4": "1e-4", "e5": "1e-5" }, { "name": "efficientnet_lite", "backend": "webnn_cpu_4", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "pass" }, { "name": "efficientnet_lite", "backend": "webgl", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "pass" }, { "name": "efficientnet_lite", "backend": "webgpu", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "pass" }, { "name": "efficientnet_lite", "backend": "webnn_gpu", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "pass" },
  { "name": "mobilenet_v2", "backend": "wasm_4", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "1e-3", "e4": "1e-4", "e5": "1e-5" }, { "name": "mobilenet_v2", "backend": "webnn_cpu_4", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "fail" }, { "name": "mobilenet_v2", "backend": "webgl", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "fail" }, { "name": "mobilenet_v2", "backend": "webgpu", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "pass" }, { "name": "mobilenet_v2", "backend": "webnn_gpu", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "fail" },
  { "name": "mobilenet_v2_12", "backend": "wasm_4", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "1e-3", "e4": "1e-4", "e5": "1e-5" }, { "name": "mobilenet_v2_12", "backend": "webnn_cpu_4", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "fail" }, { "name": "mobilenet_v2_12", "backend": "webgl", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "fail" }, { "name": "mobilenet_v2_12", "backend": "webgpu", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "pass" }, { "name": "mobilenet_v2_12", "backend": "webnn_gpu", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "fail" },
  { "name": "resnet50_v1", "backend": "wasm_4", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "1e-3", "e4": "1e-4", "e5": "1e-5" }, { "name": "resnet50_v1", "backend": "webnn_cpu_4", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "fail" }, { "name": "resnet50_v1", "backend": "webgl", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "pass" }, { "name": "resnet50_v1", "backend": "webgpu", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "fail" }, { "name": "resnet50_v1", "backend": "webnn_gpu", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "pass" },
  { "name": "resnet50_v2", "backend": "wasm_4", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "1e-3", "e4": "1e-4", "e5": "1e-5" }, { "name": "resnet50_v2", "backend": "webnn_cpu_4", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "fail" }, { "name": "resnet50_v2", "backend": "webgl", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "fail" }, { "name": "resnet50_v2", "backend": "webgpu", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "pass" }, { "name": "resnet50_v2", "backend": "webnn_gpu", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "pass" },
  { "name": "squeezenet", "backend": "wasm_4", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "1e-3", "e4": "1e-4", "e5": "1e-5" }, { "name": "squeezenet", "backend": "webnn_cpu_4", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "fail" }, { "name": "squeezenet", "backend": "webgl", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "fail" }, { "name": "squeezenet", "backend": "webgpu", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "pass" }, { "name": "squeezenet", "backend": "webnn_gpu", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "pass" },
  { "name": "tinyyolo_v2", "backend": "wasm_4", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "1e-3", "e4": "1e-4", "e5": "1e-5" }, { "name": "tinyyolo_v2", "backend": "webnn_cpu_4", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "fail" }, { "name": "tinyyolo_v2", "backend": "webgl", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "fail" }, { "name": "tinyyolo_v2", "backend": "webgpu", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "fail" }, { "name": "tinyyolo_v2", "backend": "webnn_gpu", "gpu": "NVIDIA GeForce RTX 2080 Ti Direct3D11", "e3": "pass", "e4": "pass", "e5": "fail" }]