export const fallbackEnv = {
  "windows": "Windows 11 23H2 22631.4169",
  "version": "130.0.6715.0",
  "last_update": "Sept 14, 2024"
}

export const fallback = [
  {
    "name": "florence2_decoder_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 595,
    "nodes_supported_by_webnn": 595,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "Erf",
      "Expand",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze",
      "Where"
    ]
  },
  {
    "name": "florence2_decoder_with_past_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 577,
    "nodes_supported_by_webnn": 577,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Div",
      "Erf",
      "Expand",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze",
      "Where"
    ]
  },
  {
    "name": "florence2_embed_tokens_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 2,
    "nodes_supported_by_webnn": 2,
    "supported": [
      "Cast",
      "Gather"
    ]
  },
  {
    "name": "florence2_encoder_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 343,
    "nodes_supported_by_webnn": 343,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "Erf",
      "Expand",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze",
      "Where"
    ]
  },
  {
    "name": "florence2_vision_encoder_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 5,
    "nodes_in_the_graph": 1613,
    "nodes_supported_by_webnn": 1579,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Conv",
      "Div",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Pad",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Slice",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ],
    "not_supported": [
      "Add",
      "Cast",
      "Concat",
      "Div",
      "Gather",
      "MatMul",
      "Mul",
      "Pow",
      "Range",
      "ReduceMean",
      "Reshape",
      "Shape",
      "Sqrt",
      "Sub",
      "Tile",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "llava_decoder_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 3,
    "nodes_in_the_graph": 150,
    "nodes_supported_by_webnn": 148,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Cos",
      "Div",
      "Equal",
      "Gather",
      "MatMul",
      "Mul",
      "Neg",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Sigmoid",
      "Sin",
      "Slice",
      "Softmax",
      "Sqrt",
      "Transpose",
      "Unsqueeze",
      "Where"
    ],
    "not_supported": [
      "And",
      "ScatterND"
    ]
  },
  {
    "name": "llava_embed_tokens_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 2,
    "nodes_supported_by_webnn": 2,
    "supported": [
      "Cast",
      "Gather"
    ]
  },
  {
    "name": "llava_vision_encoder_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 78,
    "nodes_supported_by_webnn": 78,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Conv",
      "Div",
      "Erf",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Sigmoid",
      "Slice",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose"
    ]
  },
  {
    "name": "moondream2_embed_tokens_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 2,
    "nodes_supported_by_webnn": 2,
    "supported": [
      "Cast",
      "Gather"
    ]
  },
  {
    "name": "moondream2_vision_encoder_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 1515,
    "nodes_supported_by_webnn": 1515,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Split",
      "Sqrt",
      "Squeeze",
      "Sub",
      "Tanh",
      "Transpose"
    ]
  },
  {
    "name": "florence2_conditional_decoder_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 105,
    "nodes_supported_by_webnn": 105,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "Erf",
      "Expand",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze",
      "Where"
    ]
  },
  {
    "name": "florence2_conditional_decoder_merged_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 100,
    "nodes_supported_by_webnn": 100,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Div",
      "Erf",
      "Expand",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze",
      "Where"
    ],
    "not_supported": [
      "If"
    ]
  },
  {
    "name": "florence2_conditional_decoder_with_past_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 100,
    "nodes_supported_by_webnn": 100,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Div",
      "Erf",
      "Expand",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze",
      "Where"
    ]
  },
  {
    "name": "florence2_conditional_decoder_with_past_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 100,
    "nodes_supported_by_webnn": 100,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Div",
      "Erf",
      "Expand",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze",
      "Where"
    ]
  },
  {
    "name": "florence2_conditional_embed_tokens_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 1,
    "nodes_supported_by_webnn": 1,
    "supported": [
      "Gather"
    ]
  },
  {
    "name": "florence2_conditional_encoder_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 323,
    "nodes_supported_by_webnn": 323,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "Erf",
      "Expand",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze",
      "Where"
    ]
  },
  {
    "name": "florence2_conditional_vision_encoder_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 1609,
    "nodes_supported_by_webnn": 1609,
    "supported": [
      "Add",
      "Concat",
      "Conv",
      "Div",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Pad",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Slice",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose"
    ]
  },
  {
    "name": "llava_phi_embed_tokens_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 1,
    "nodes_supported_by_webnn": 1,
    "supported": [
      "Gather"
    ]
  },
  {
    "name": "llava_phi_vision_encoder_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 76,
    "nodes_supported_by_webnn": 76,
    "supported": [
      "Add",
      "Concat",
      "Conv",
      "Div",
      "Erf",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Sigmoid",
      "Slice",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose"
    ]
  }
]