export const fallbackEnv = {
  "windows": "Windows 11 23H2 22631.3737",
  "version": "128.0.6591.0",
  "last_update": "July 12, 2024"
}
export const fallback = [
  {
    "name": "univar_lambda_1_fp32",
    "backend": "gpu",
    "error": "Failed to execute 'slice' on 'MLGraphBuilder': For dimension (3): the starting index to slice must be less than input size (64).",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 644,
    "nodes_supported_by_webnn": 644,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Div",
      "Gather",
      "LayerNormalization",
      "MatMul",
      "Mul",
      "Neg",
      "Reshape",
      "Sigmoid",
      "Slice",
      "Softmax",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "bge_large_en_v1_5_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 1218,
    "nodes_supported_by_webnn": 1218,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "bge_reranker_base_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 2,
    "nodes_in_the_graph": 629,
    "nodes_supported_by_webnn": 628,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "Equal",
      "Erf",
      "Gather",
      "Gemm",
      "MatMul",
      "Mul",
      "Not",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Tanh",
      "Transpose",
      "Unsqueeze"
    ],
    "not_supported": ["CumSum"]
  },
  {
    "name": "detr_resnet_50_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 8,
    "nodes_in_the_graph": 1017,
    "nodes_supported_by_webnn": 1010,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Conv",
      "Cos",
      "Div",
      "Expand",
      "Flatten",
      "Gather",
      "MatMul",
      "MaxPool",
      "Mul",
      "Pow",
      "ReduceMean",
      "Relu",
      "Reshape",
      "Sigmoid",
      "Sin",
      "Slice",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze",
      "Where"
    ],
    "not_supported": ["CumSum", "Resize", "Slice"]
  },
  {
    "name": "distil_medium_en_decoder_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 191,
    "nodes_supported_by_webnn": 191,
    "supported": [
      "Add",
      "Div",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose"
    ]
  },
  {
    "name": "distil_medium_en_decoder_merged_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 3,
    "nodes_in_the_graph": 177,
    "nodes_supported_by_webnn": 165,
    "supported": [
      "Add",
      "Concat",
      "Div",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose"
    ],
    "not_supported": [
      "MatMul",
      "Reshape",
      "Softmax",
      "Transpose"
    ]
  },
  {
    "name": "distil_medium_en_decoder_with_past_fp32",
    "backend": "gpu",
    "error": ""
  },
  {
    "name": "distil_medium_en_encoder_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 1295,
    "nodes_supported_by_webnn": 1295,
    "supported": [
      "Add",
      "Conv",
      "Div",
      "Erf",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose"
    ]
  },
  {
    "name": "distiluse_base_multilingual_cased_v2_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 324,
    "nodes_supported_by_webnn": 324,
    "supported": [
      "Add",
      "Div",
      "Equal",
      "Erf",
      "Expand",
      "Gather",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Where"
    ]
  },
  {
    "name": "efficientnet_lite",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 180,
    "nodes_supported_by_webnn": 180,
    "supported": [
      "Add",
      "AveragePool",
      "Clip",
      "Conv",
      "Gemm",
      "Softmax",
      "Squeeze",
      "Transpose"
    ]
  },
  {
    "name": "face_parsing_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 5,
    "nodes_in_the_graph": 3621,
    "nodes_supported_by_webnn": 3617,
    "supported": [
      "Add",
      "Concat",
      "Conv",
      "Div",
      "Erf",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Relu",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose"
    ],
    "not_supported": ["Resize"]
  },
  {
    "name": "gte_base_en_v1_5_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 759,
    "nodes_supported_by_webnn": 759,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Div",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Neg",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Slice",
      "Softmax",
      "Split",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "gte_small_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 618,
    "nodes_supported_by_webnn": 618,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "jina_clip_v1_text_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 588,
    "nodes_supported_by_webnn": 588,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "Einsum",
      "Equal",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Not",
      "Pow",
      "ReduceMean",
      "ReduceSum",
      "Reshape",
      "Slice",
      "Softmax",
      "Split",
      "Sqrt",
      "Squeeze",
      "Sub",
      "Unsqueeze",
      "Where"
    ]
  },
  {
    "name": "jina_clip_v1_vision_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 1215,
    "nodes_supported_by_webnn": 1215,
    "supported": [
      "Add",
      "Concat",
      "Conv",
      "Div",
      "Gather",
      "MatMul",
      "Mul",
      "Neg",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Sigmoid",
      "Slice",
      "Softmax",
      "Split",
      "Sqrt",
      "Squeeze",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "jina_embeddings_v2_base_code_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 988,
    "nodes_supported_by_webnn": 988,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Slice",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "jina_reranker_v1_turbo_en_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 338,
    "nodes_supported_by_webnn": 338,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "Erf",
      "Gather",
      "Gemm",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Slice",
      "Softmax",
      "Sqrt",
      "Sub",
      "Tanh",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "llama2_c_stories15m_decoder_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 335,
    "nodes_supported_by_webnn": 335,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Div",
      "Expand",
      "Gather",
      "MatMul",
      "Mul",
      "Neg",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Sigmoid",
      "Slice",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze",
      "Where"
    ]
  },
  {
    "name": "llama2_c_stories15m_decoder_merged_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 346,
    "nodes_supported_by_webnn": 346,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Div",
      "Expand",
      "Gather",
      "MatMul",
      "Mul",
      "Neg",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Sigmoid",
      "Slice",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze",
      "Where"
    ]
  },
  {
    "name": "llama2_c_stories15m_decoder_with_past_fp32",
    "backend": "gpu",
    "error": "",
    "not_supported": ["Identity", "Squeeze"]
  },
  {
    "name": "mobilenet_v2_10",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 100,
    "nodes_supported_by_webnn": 100,
    "supported": ["Add", "Clip", "Conv", "Gemm", "GlobalAveragePool", "Reshape"]
  },
  {
    "name": "mobilenet_v2_12",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 100,
    "nodes_supported_by_webnn": 100,
    "supported": ["Add", "Clip", "Conv", "Gemm", "GlobalAveragePool", "Reshape"]
  },
  {
    "name": "mobilenet_v2_7",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 102,
    "nodes_supported_by_webnn": 102,
    "supported": ["Add", "Conv", "GlobalAveragePool", "Relu", "Reshape"]
  },
  {
    "name": "mobilenet_v3",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 122,
    "nodes_supported_by_webnn": 122,
    "supported": [
      "Add",
      "Conv",
      "Flatten",
      "Gemm",
      "GlobalAveragePool",
      "HardSigmoid",
      "HardSwish",
      "Mul",
      "ReduceMean",
      "Relu"
    ]
  },
  {
    "name": "mobilevit_small_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 563,
    "nodes_supported_by_webnn": 563,
    "supported": [
      "Add",
      "Concat",
      "Conv",
      "Div",
      "Gemm",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Sigmoid",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose"
    ]
  },
  {
    "name": "mxbai_embed_large_v1_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 1218,
    "nodes_supported_by_webnn": 1218,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "mxbai_rerank_base_v1_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 25,
    "nodes_in_the_graph": 832,
    "nodes_supported_by_webnn": 808,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "Erf",
      "Gather",
      "Gemm",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Squeeze",
      "Sub",
      "Transpose",
      "Unsqueeze",
      "Where"
    ],
    "not_supported": ["GatherElements"]
  },
  {
    "name": "nomic_embed_text_v1_fp32",
    "backend": "gpu",
    "error": "Failed to execute 'slice' on 'MLGraphBuilder': For dimension (3): the starting index to slice must be less than input size (64).",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 845,
    "nodes_supported_by_webnn": 845,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Div",
      "Gather",
      "MatMul",
      "Mul",
      "Neg",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Sigmoid",
      "Slice",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "nomic_embed_text_v1_5_fp32",
    "backend": "gpu",
    "error": "Failed to execute 'slice' on 'MLGraphBuilder': For dimension (3): the starting index to slice must be less than input size (64).",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 845,
    "nodes_supported_by_webnn": 845,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Div",
      "Gather",
      "MatMul",
      "Mul",
      "Neg",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Sigmoid",
      "Slice",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "paraphrase_multilingual_mpnet_base_v2_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 2,
    "nodes_in_the_graph": 625,
    "nodes_supported_by_webnn": 624,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "Equal",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Not",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ],
    "not_supported": ["CumSum"]
  },
  {
    "name": "resnet50_v1",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 122,
    "nodes_supported_by_webnn": 122,
    "supported": [
      "Add",
      "Conv",
      "Flatten",
      "Gemm",
      "GlobalAveragePool",
      "MaxPool",
      "Relu"
    ]
  },
  {
    "name": "resnet50_v2",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 141,
    "nodes_supported_by_webnn": 141,
    "supported": [
      "Add",
      "BatchNormalization",
      "Conv",
      "Gemm",
      "GlobalAveragePool",
      "MaxPool",
      "Relu",
      "Reshape"
    ]
  },
  {
    "name": "sam_b_decoder",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 3,
    "nodes_in_the_graph": 349,
    "nodes_supported_by_webnn": 345,
    "supported": [
      "Add",
      "ArgMax",
      "Cast",
      "Concat",
      "Conv",
      "ConvTranspose",
      "Cos",
      "Div",
      "Equal",
      "Erf",
      "Expand",
      "Flatten",
      "Floor",
      "Gather",
      "Gemm",
      "LayerNormalization",
      "MatMul",
      "Mul",
      "Not",
      "Pow",
      "Reciprocal",
      "ReduceMax",
      "ReduceMean",
      "Relu",
      "Reshape",
      "Resize",
      "Sin",
      "Slice",
      "Softmax",
      "Split",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ],
    "not_supported": ["Resize", "Shape", "Slice"]
  },
  {
    "name": "sam_b_encoder",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 593,
    "nodes_supported_by_webnn": 593,
    "supported": [
      "Add",
      "Conv",
      "Div",
      "Einsum",
      "Erf",
      "LayerNormalization",
      "MatMul",
      "Mul",
      "Pad",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Slice",
      "Softmax",
      "Split",
      "Sqrt",
      "Squeeze",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "sam_vit_base_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 4,
    "nodes_in_the_graph": 1135,
    "nodes_supported_by_webnn": 1132,
    "supported": [
      "Add",
      "Concat",
      "Conv",
      "ConvTranspose",
      "Cos",
      "Div",
      "Einsum",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Pad",
      "Pow",
      "ReduceMean",
      "Relu",
      "Reshape",
      "Sin",
      "Slice",
      "Softmax",
      "Split",
      "Sqrt",
      "Squeeze",
      "Sub",
      "Transpose",
      "Unsqueeze",
      "Where"
    ],
    "not_supported": ["ScatterND", "Tile"]
  },
  {
    "name": "sam_vit_base_prompt_encoder_mask_decoder_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 5,
    "nodes_in_the_graph": 362,
    "nodes_supported_by_webnn": 358,
    "supported": [
      "Add",
      "Concat",
      "ConvTranspose",
      "Cos",
      "Div",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Relu",
      "Reshape",
      "Sin",
      "Slice",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze",
      "Where"
    ],
    "not_supported": ["ScatterND", "Tile"]
  },
  {
    "name": "sam_vit_base_vision_encoder_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 781,
    "nodes_supported_by_webnn": 781,
    "supported": [
      "Add",
      "Conv",
      "Div",
      "Einsum",
      "Erf",
      "MatMul",
      "Mul",
      "Pad",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Slice",
      "Softmax",
      "Split",
      "Sqrt",
      "Squeeze",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "sd_2_1_vae_decoder",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 292,
    "nodes_supported_by_webnn": 292,
    "supported": [
      "Add",
      "Cast",
      "Conv",
      "Div",
      "InstanceNormalization",
      "MatMul",
      "Mul",
      "Reshape",
      "Resize",
      "Sigmoid",
      "Softmax",
      "Sqrt",
      "Transpose"
    ]
  },
  {
    "name": "sd_2_1_vae_encoder",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 224,
    "nodes_supported_by_webnn": 223,
    "supported": [
      "Add",
      "Clip",
      "Conv",
      "Exp",
      "InstanceNormalization",
      "MatMul",
      "Mul",
      "Reshape",
      "Sigmoid",
      "Slice",
      "Softmax",
      "Transpose"
    ],
    "not_supported": ["RandomNormalLike"]
  },
  {
    "name": "sd_turbo_text_encoder_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 1330,
    "nodes_supported_by_webnn": 1330,
    "supported": [
      "Add",
      "ArgMax",
      "Cast",
      "Div",
      "Erf",
      "Flatten",
      "Gather",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose"
    ]
  },
  {
    "name": "sd_turbo_unet_fp32",
    "backend": "gpu",
    "error": "Aborted(). Build with -sASSERTIONS for more info."
  },
  {
    "name": "sd_turbo_vae_decoder_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 297,
    "nodes_supported_by_webnn": 297,
    "supported": [
      "Add",
      "Cast",
      "Conv",
      "Div",
      "InstanceNormalization",
      "MatMul",
      "Mul",
      "Reshape",
      "Resize",
      "Sigmoid",
      "Softmax",
      "Sqrt",
      "Transpose"
    ]
  },
  {
    "name": "segment_anything_decoder",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 3,
    "nodes_in_the_graph": 349,
    "nodes_supported_by_webnn": 345,
    "supported": [
      "Add",
      "ArgMax",
      "Cast",
      "Concat",
      "Conv",
      "ConvTranspose",
      "Cos",
      "Div",
      "Equal",
      "Erf",
      "Expand",
      "Flatten",
      "Floor",
      "Gather",
      "Gemm",
      "LayerNormalization",
      "MatMul",
      "Mul",
      "Not",
      "Pow",
      "Reciprocal",
      "ReduceMax",
      "ReduceMean",
      "Relu",
      "Reshape",
      "Resize",
      "Sin",
      "Slice",
      "Softmax",
      "Split",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ],
    "not_supported": ["Resize", "Shape", "Slice"]
  },
  {
    "name": "snowflake_arctic_embed_m_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 618,
    "nodes_supported_by_webnn": 618,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "squeezebert_uncased_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 536,
    "nodes_supported_by_webnn": 536,
    "supported": [
      "Add",
      "Cast",
      "Conv",
      "Div",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "squeezenet",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 65,
    "nodes_supported_by_webnn": 65,
    "supported": ["AveragePool", "Concat", "Conv", "MaxPool", "Relu", "Reshape"]
  },
  {
    "name": "tinyllama_1_1b_chat_v1_0_merged_fp32",
    "backend": "gpu",
    "error": "WebAssembly.Memory(): Property 'initial': value 67142 is above the upper bound 65536"
  },
  {
    "name": "tinyllama_v0_decoder_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 441,
    "nodes_supported_by_webnn": 441,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Div",
      "Expand",
      "Gather",
      "MatMul",
      "Mul",
      "Neg",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Sigmoid",
      "Slice",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze",
      "Where"
    ]
  },
  {
    "name": "tinyllama_v0_decoder_merged_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 456,
    "nodes_supported_by_webnn": 456,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Div",
      "Expand",
      "Gather",
      "MatMul",
      "Mul",
      "Neg",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Sigmoid",
      "Slice",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze",
      "Where"
    ]
  },
  {
    "name": "tinyllama_v0_decoder_with_past_fp32",
    "backend": "gpu",
    "error": "",
    "not_supported": ["Identity", "Squeeze"]
  },
  {
    "name": "uae_large_v1_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 1218,
    "nodes_supported_by_webnn": 1218,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "whisper_base_decoder_static_merged",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 530,
    "nodes_supported_by_webnn": 530,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Div",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze",
      "Where"
    ]
  },
  {
    "name": "whisper_base_decoder_static",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 562,
    "nodes_supported_by_webnn": 562,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "Erf",
      "Expand",
      "Gather",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze",
      "Where"
    ]
  },
  {
    "name": "whisper_base_encoder",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 341,
    "nodes_supported_by_webnn": 341,
    "supported": [
      "Add",
      "Conv",
      "Div",
      "Erf",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose"
    ]
  },
  {
    "name": "yolov8n_pose_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 267,
    "nodes_supported_by_webnn": 267,
    "supported": [
      "Add",
      "Concat",
      "Conv",
      "Div",
      "MaxPool",
      "Mul",
      "Reshape",
      "Resize",
      "Sigmoid",
      "Slice",
      "Softmax",
      "Split",
      "Sub",
      "Transpose"
    ]
  },
  {
    "name": "yolov8x_pose_fp32",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 399,
    "nodes_supported_by_webnn": 399,
    "supported": [
      "Add",
      "Concat",
      "Conv",
      "Div",
      "MaxPool",
      "Mul",
      "Reshape",
      "Resize",
      "Sigmoid",
      "Slice",
      "Softmax",
      "Split",
      "Sub",
      "Transpose"
    ]
  },
  {
    "name": "univar_lambda_1_fp16",
    "backend": "gpu",
    "error": "Failed to execute 'slice' on 'MLGraphBuilder': For dimension (3): the starting index to slice must be less than input size (64).",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 655,
    "nodes_supported_by_webnn": 655,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Cos",
      "Div",
      "Einsum",
      "Expand",
      "Gather",
      "LayerNormalization",
      "MatMul",
      "Mul",
      "Neg",
      "Reshape",
      "Sigmoid",
      "Sin",
      "Slice",
      "Softmax",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "bge_large_en_v1_5_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 1219,
    "nodes_supported_by_webnn": 1219,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "bge_reranker_base_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 2,
    "nodes_in_the_graph": 630,
    "nodes_supported_by_webnn": 629,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "Equal",
      "Erf",
      "Gather",
      "Gemm",
      "MatMul",
      "Mul",
      "Not",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Tanh",
      "Transpose",
      "Unsqueeze"
    ],
    "not_supported": ["CumSum"]
  },
  {
    "name": "detr_resnet_50_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 9,
    "nodes_in_the_graph": 1069,
    "nodes_supported_by_webnn": 1061,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Conv",
      "Cos",
      "Div",
      "Expand",
      "Flatten",
      "Gather",
      "MatMul",
      "MaxPool",
      "Mul",
      "Pow",
      "ReduceMean",
      "Relu",
      "Reshape",
      "Sigmoid",
      "Sin",
      "Slice",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze",
      "Where"
    ],
    "not_supported": ["CumSum", "Resize", "Slice", "Tile"]
  },
  {
    "name": "distiluse_base_multilingual_cased_v2_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 325,
    "nodes_supported_by_webnn": 325,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "Equal",
      "Erf",
      "Expand",
      "Gather",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Where"
    ]
  },
  {
    "name": "efficientnet_lite_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 180,
    "nodes_supported_by_webnn": 180,
    "supported": [
      "Add",
      "AveragePool",
      "Clip",
      "Conv",
      "Gemm",
      "Softmax",
      "Squeeze",
      "Transpose"
    ]
  },
  {
    "name": "gte_base_en_v1_5_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 760,
    "nodes_supported_by_webnn": 760,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Div",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Neg",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Slice",
      "Softmax",
      "Split",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "gte_small_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 619,
    "nodes_supported_by_webnn": 619,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "jina_clip_v1_text_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 589,
    "nodes_supported_by_webnn": 589,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "Einsum",
      "Equal",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Not",
      "Pow",
      "ReduceMean",
      "ReduceSum",
      "Reshape",
      "Slice",
      "Softmax",
      "Split",
      "Sqrt",
      "Squeeze",
      "Sub",
      "Unsqueeze",
      "Where"
    ]
  },
  {
    "name": "jina_clip_v1_vision_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 1217,
    "nodes_supported_by_webnn": 1217,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Conv",
      "Div",
      "Gather",
      "MatMul",
      "Mul",
      "Neg",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Sigmoid",
      "Slice",
      "Softmax",
      "Split",
      "Sqrt",
      "Squeeze",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "jina_embeddings_v2_base_code_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 991,
    "nodes_supported_by_webnn": 991,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Slice",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "jina_reranker_v1_turbo_en_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 343,
    "nodes_supported_by_webnn": 343,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "Erf",
      "Gather",
      "Gemm",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Slice",
      "Softmax",
      "Sqrt",
      "Sub",
      "Tanh",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "llama2_c_stories15m_decoder_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 350,
    "nodes_supported_by_webnn": 350,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Div",
      "Expand",
      "Gather",
      "MatMul",
      "Mul",
      "Neg",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Sigmoid",
      "Slice",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze",
      "Where"
    ]
  },
  {
    "name": "mobilenet_v2_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 100,
    "nodes_supported_by_webnn": 100,
    "supported": ["Add", "Clip", "Conv", "Reshape"]
  },
  {
    "name": "mobilevit_small_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 565,
    "nodes_supported_by_webnn": 565,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Conv",
      "Div",
      "Gemm",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Sigmoid",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose"
    ]
  },
  {
    "name": "mxbai_embed_large_v1_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 1219,
    "nodes_supported_by_webnn": 1219,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "paraphrase_multilingual_mpnet_base_v2_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 2,
    "nodes_in_the_graph": 626,
    "nodes_supported_by_webnn": 625,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "Equal",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Not",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ],
    "not_supported": ["CumSum"]
  },
  {
    "name": "resnet50_v1_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 122,
    "nodes_supported_by_webnn": 122,
    "supported": [
      "Add",
      "Conv",
      "Flatten",
      "Gemm",
      "GlobalAveragePool",
      "MaxPool",
      "Relu"
    ]
  },
  {
    "name": "sam_vit_base_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 6,
    "nodes_in_the_graph": 1353,
    "nodes_supported_by_webnn": 1347,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Conv",
      "ConvTranspose",
      "Cos",
      "Div",
      "Einsum",
      "Equal",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Neg",
      "Pad",
      "Pow",
      "ReduceMean",
      "Relu",
      "Reshape",
      "Sin",
      "Slice",
      "Softmax",
      "Split",
      "Sqrt",
      "Squeeze",
      "Sub",
      "Transpose",
      "Unsqueeze",
      "Where"
    ],
    "not_supported": ["ScatterND", "Tile"]
  },
  {
    "name": "sam_vit_base_prompt_encoder_mask_decoder_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 6,
    "nodes_in_the_graph": 378,
    "nodes_supported_by_webnn": 373,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "ConvTranspose",
      "Cos",
      "Div",
      "Equal",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Neg",
      "Pow",
      "ReduceMean",
      "Relu",
      "Reshape",
      "Sin",
      "Slice",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze",
      "Where"
    ],
    "not_supported": ["ScatterND", "Tile"]
  },
  {
    "name": "sam_vit_base_vision_encoder_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 2,
    "nodes_in_the_graph": 984,
    "nodes_supported_by_webnn": 983,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Conv",
      "Cos",
      "Div",
      "Einsum",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Pad",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Sin",
      "Slice",
      "Softmax",
      "Split",
      "Sqrt",
      "Squeeze",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ],
    "not_supported": ["Tile"]
  },
  {
    "name": "sd_vae_decoder_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 355,
    "nodes_supported_by_webnn": 355,
    "supported": [
      "Add",
      "Cast",
      "Conv",
      "InstanceNormalization",
      "MatMul",
      "Mul",
      "Reshape",
      "Resize",
      "Sigmoid",
      "Softmax",
      "Transpose"
    ]
  },
  {
    "name": "sd_1_5_text_encoder_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 2,
    "nodes_in_the_graph": 479,
    "nodes_supported_by_webnn": 478,
    "supported": [
      "Add",
      "ArgMax",
      "Flatten",
      "Gather",
      "LayerNormalization",
      "MatMul",
      "Mul",
      "Reshape",
      "Sigmoid",
      "Softmax",
      "Transpose",
      "Unsqueeze"
    ],
    "not_supported": ["Trilu"]
  },
  {
    "name": "sd_1_5_unet_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 1834,
    "nodes_supported_by_webnn": 1834,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Conv",
      "Cos",
      "Div",
      "Erf",
      "Expand",
      "Gemm",
      "InstanceNormalization",
      "LayerNormalization",
      "MatMul",
      "Mul",
      "Reshape",
      "Resize",
      "Sigmoid",
      "Sin",
      "Slice",
      "Softmax",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "sd_safety_checker_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 901,
    "nodes_supported_by_webnn": 901,
    "supported": [
      "Add",
      "Cast",
      "Clip",
      "Concat",
      "Conv",
      "Div",
      "Expand",
      "Gather",
      "Gemm",
      "Greater",
      "LayerNormalization",
      "MatMul",
      "Mul",
      "ReduceL2",
      "ReduceSum",
      "Reshape",
      "Sigmoid",
      "Softmax",
      "Sub",
      "Transpose",
      "Unsqueeze",
      "Where"
    ]
  },
  {
    "name": "sd_turbo_text_encoder_layernorm_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 953,
    "nodes_supported_by_webnn": 953,
    "supported": [
      "Add",
      "ArgMax",
      "Cast",
      "Div",
      "Erf",
      "Flatten",
      "Gather",
      "LayerNormalization",
      "MatMul",
      "Mul",
      "Reshape",
      "Softmax",
      "Transpose"
    ]
  },
  {
    "name": "sd_turbo_text_encoder_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 1329,
    "nodes_supported_by_webnn": 1329,
    "supported": [
      "Add",
      "ArgMax",
      "Cast",
      "Div",
      "Erf",
      "Flatten",
      "Gather",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose"
    ]
  },
  {
    "name": "sd_turbo_unet_layernorm_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 1740,
    "nodes_supported_by_webnn": 1740,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Conv",
      "Cos",
      "Div",
      "Erf",
      "Expand",
      "Gemm",
      "InstanceNormalization",
      "LayerNormalization",
      "MatMul",
      "Mul",
      "Reshape",
      "Resize",
      "Sigmoid",
      "Sin",
      "Slice",
      "Softmax",
      "Sqrt",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "sd_turbo_unet_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 2124,
    "nodes_supported_by_webnn": 2124,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Conv",
      "Cos",
      "Div",
      "Erf",
      "Expand",
      "Gemm",
      "InstanceNormalization",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Resize",
      "Sigmoid",
      "Sin",
      "Slice",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "segment_anything_decoder_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 4,
    "nodes_in_the_graph": 377,
    "nodes_supported_by_webnn": 370,
    "supported": [
      "Add",
      "ArgMax",
      "Cast",
      "Concat",
      "Conv",
      "ConvTranspose",
      "Cos",
      "Div",
      "Equal",
      "Erf",
      "Expand",
      "Flatten",
      "Floor",
      "Gather",
      "Gemm",
      "LayerNormalization",
      "MatMul",
      "Mul",
      "Not",
      "Pow",
      "Reciprocal",
      "ReduceMax",
      "ReduceMean",
      "Relu",
      "Reshape",
      "Resize",
      "Sin",
      "Slice",
      "Softmax",
      "Split",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ],
    "not_supported": ["Cast", "Resize", "Shape", "Slice"]
  },
  {
    "name": "segment_anything_encoder_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 782,
    "nodes_supported_by_webnn": 782,
    "supported": [
      "Add",
      "Cast",
      "Conv",
      "Div",
      "Einsum",
      "Erf",
      "Gather",
      "LayerNormalization",
      "MatMul",
      "Mul",
      "Pad",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Slice",
      "Softmax",
      "Split",
      "Sqrt",
      "Squeeze",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "snowflake_arctic_embed_m_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 619,
    "nodes_supported_by_webnn": 619,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "squeezebert_uncased_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 537,
    "nodes_supported_by_webnn": 537,
    "supported": [
      "Add",
      "Cast",
      "Conv",
      "Div",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "squeezenet_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 65,
    "nodes_supported_by_webnn": 65,
    "supported": [
      "Concat",
      "Conv",
      "GlobalAveragePool",
      "MaxPool",
      "Relu",
      "Softmax"
    ]
  },
  {
    "name": "tinyllama_1_1b_chat_v1_0_merged_fp16",
    "backend": "gpu"
  },
  {
    "name": "tinyllama_v0_decoder_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 460,
    "nodes_supported_by_webnn": 460,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Div",
      "Expand",
      "Gather",
      "MatMul",
      "Mul",
      "Neg",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Sigmoid",
      "Slice",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze",
      "Where"
    ]
  },
  {
    "name": "uae_large_v1_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 1219,
    "nodes_supported_by_webnn": 1219,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "Erf",
      "Gather",
      "MatMul",
      "Mul",
      "Pow",
      "ReduceMean",
      "Reshape",
      "Softmax",
      "Sqrt",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ]
  },
  {
    "name": "whisper_base_decoder_static_gelu_4dmask_fp16_merged",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 348,
    "nodes_supported_by_webnn": 348,
    "supported": [
      "Add",
      "Concat",
      "Gather",
      "Gelu",
      "LayerNormalization",
      "MatMul",
      "Mul",
      "Reshape",
      "Softmax",
      "Transpose"
    ]
  },
  {
    "name": "whisper_base_decoder_static_gelu_fp16_merged",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 354,
    "nodes_supported_by_webnn": 354,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Gather",
      "Gelu",
      "LayerNormalization",
      "MatMul",
      "Mul",
      "Reshape",
      "Softmax",
      "Sub",
      "Transpose",
      "Unsqueeze",
      "Where"
    ]
  },
  {
    "name": "whisper_base_decoder_static_fp16_merged",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 378,
    "nodes_supported_by_webnn": 378,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Div",
      "Erf",
      "Gather",
      "LayerNormalization",
      "MatMul",
      "Mul",
      "Reshape",
      "Softmax",
      "Sub",
      "Transpose",
      "Unsqueeze",
      "Where"
    ]
  },
  {
    "name": "whisper_base_decoder_static_gelu_4dmask_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 377,
    "nodes_supported_by_webnn": 377,
    "supported": [
      "Add",
      "Gather",
      "Gelu",
      "LayerNormalization",
      "MatMul",
      "Mul",
      "Reshape",
      "Softmax",
      "Transpose"
    ]
  },
  {
    "name": "whisper_base_decoder_static_gelu_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 386,
    "nodes_supported_by_webnn": 386,
    "supported": [
      "Add",
      "Cast",
      "Expand",
      "Gather",
      "Gelu",
      "LayerNormalization",
      "MatMul",
      "Mul",
      "Reshape",
      "Softmax",
      "Sub",
      "Transpose",
      "Unsqueeze",
      "Where"
    ]
  },
  {
    "name": "whisper_base_decoder_static_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 410,
    "nodes_supported_by_webnn": 410,
    "supported": [
      "Add",
      "Cast",
      "Div",
      "Erf",
      "Expand",
      "Gather",
      "LayerNormalization",
      "MatMul",
      "Mul",
      "Reshape",
      "Softmax",
      "Sub",
      "Transpose",
      "Unsqueeze",
      "Where"
    ]
  },
  {
    "name": "whisper_base_encoder_gelu_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 205,
    "nodes_supported_by_webnn": 205,
    "supported": [
      "Add",
      "Conv",
      "Gelu",
      "LayerNormalization",
      "MatMul",
      "Mul",
      "Reshape",
      "Softmax",
      "Transpose"
    ]
  },
  {
    "name": "whisper_base_encoder_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 237,
    "nodes_supported_by_webnn": 237,
    "supported": [
      "Add",
      "Conv",
      "Div",
      "Erf",
      "LayerNormalization",
      "MatMul",
      "Mul",
      "Reshape",
      "Softmax",
      "Transpose"
    ]
  },
  {
    "name": "yolov8n_pose_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 273,
    "nodes_supported_by_webnn": 273,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Conv",
      "Div",
      "Flatten",
      "MatMul",
      "MaxPool",
      "Mul",
      "ReduceMax",
      "Reshape",
      "Resize",
      "Sigmoid",
      "Slice",
      "Softmax",
      "Split",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ],
    "not_supported": ["GatherElements", "Mod", "Tile", "TopK"]
  },
  {
    "name": "yolov8x_pose_fp16",
    "backend": "gpu",
    "error": "",
    "partitions_supported_by_webnn": 1,
    "nodes_in_the_graph": 405,
    "nodes_supported_by_webnn": 405,
    "supported": [
      "Add",
      "Cast",
      "Concat",
      "Conv",
      "Div",
      "Flatten",
      "MatMul",
      "MaxPool",
      "Mul",
      "ReduceMax",
      "Reshape",
      "Resize",
      "Sigmoid",
      "Slice",
      "Softmax",
      "Split",
      "Sub",
      "Transpose",
      "Unsqueeze"
    ],
    "not_supported": ["GatherElements", "Mod", "Tile", "TopK"]
  }
]